src/processos/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('registro/', views.Registro.as_view(), name='registro'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', views.logout, name='logout'),
    path('processos/', views.get_user_processos, name='processos'),
    path('processos/new/', views.add_user_processo, name='add_processos'),
    path('processos/<int:id_processo>/view/', views.view_user_processo, name='view_processo'),
    path('processos/<int:id_processo>/view/requerimento/', views.requerimento, name='requerimento'),
    path('processos/<int:id_processo>/edit/', views.edit_user_processo, name='edit_processo'),
    path('processos/clone/', views.clone_user_processo, name='clone_processo'),
    path('processos/remove/', views.remove_user_processo, name='remove_process'),
    path('dados/', views.get_user_data, name='user_data'),
    path('dados/new/', views.add_user_data, name='add_user_data'),
    path('dados/<int:id_data>/edit/', views.edit_user_data, name='edit_user_data'),
    # path('dados/<int:id>/', views.add_edit_user_data, name='add_edit_user_data')
]

src/sistema_processos/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('processos.urls')),
]

src/processos/models.py
from datetime import date
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.
class User(AbstractUser):
    matricula = models.CharField(unique=True, max_length=9)

    USERNAME_FIELD = 'matricula'


class UserData(models.Model):
    nome = models.CharField(max_length=255)
    doc_identificacao = models.CharField(max_length=12)
    doc_tipo = models.CharField(max_length=40)
    endereco = models.CharField(max_length=255)
    bairro = models.CharField(max_length=40)
    telefone = models.CharField(max_length=15)
    cep = models.CharField(max_length=9, blank=False, null=False)
    curso = models.CharField(max_length=100)

    aluno = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )

    def __str__(self):
        return self.nome + ', ' + self.doc_identificacao + ', ' + self.curso


class Processo(models.Model):
    numero = models.CharField(max_length=18, blank=True)
    tipo_processo = models.TextField(blank=False)
    esclarecimentos = models.TextField(blank=False)
    natureza_processo = models.CharField(max_length=100)
    parecer = models.CharField(max_length=40)

    user_data = models.ForeignKey(
        UserData,
        on_delete=models.SET_NULL,
        null=True
    )

    aluno = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )

src/processos/forms.py
import datetime

from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import User, UserData, Processo

class CustomUserCreateForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = User
        fields = ('email', 'matricula')


class CustomUserChangeForm(UserChangeForm):

    class Meta(UserChangeForm):
        model = User
        fields = ('email', 'matricula')

class UserDataForm(forms.ModelForm):

    class Meta:
        model = UserData
        fields = ('nome', 'doc_identificacao', 'doc_tipo',
            'endereco', 'bairro', 'telefone', 'curso')

    nome = forms.CharField(
        label='Nome do Requerente',
        widget=forms.TextInput(attrs={
            'class': 'form-control form-control-alternative'}),
        required=True
    )

    doc_identificacao = forms.CharField(
        label='Documento de Identificação',
        widget=forms.TextInput(attrs={
            'class': 'form-control form-control-alternative'}),
        required=True
    )

    doc_tipo = forms.CharField(
        label='Tipo de documento',
        widget=forms.TextInput(attrs={
            'class': 'form-control form-control-alternative'}),
        required=True
    )

    endereco = forms.CharField(
        label='Endereço',
        widget=forms.TextInput(attrs={
            'class': 'form-control form-control-alternative'}),
        required=True
    )

    bairro = forms.CharField(
        label='Bairro',
        widget=forms.TextInput(attrs={
            'class': 'form-control form-control-alternative'}),
        required=True
    )

    telefone = forms.CharField(
        label='Telefone',
        widget=forms.TextInput(attrs={
            'class': 'form-control form-control-alternative'}),
        required=True
    )

    cep = forms.CharField(
        label='CEP',
        widget=forms.TextInput(attrs={
            'class': 'form-control form-control-alternative'}),
        required=True
    )

    curso = forms.CharField(
        label='Curso',
        widget=forms.TextInput(attrs={
            'class': 'form-control form-control-alternative'}),
        required=True
    )

class ProcessoForm(forms.ModelForm):
    
    class Meta:
        model = Processo
        fields = ('numero', 'esclarecimentos', 'tipo_processo',
            'natureza_processo', 'parecer', 'user_data')

    numero = forms.CharField(
        label='Número do Processo',
        widget=forms.TextInput(attrs={
            'class': 'form-control form-control-alternative'}),
        required=False
    )

    tipo_processo = forms.CharField(
        label='Objeto do requerimento',
        widget=forms.Textarea(),
        required=False
    )

    esclarecimentos = forms.CharField(
        label='Esclarecimentos',
        widget=forms.Textarea(),
        required=True
    )

    natureza_processo = forms.CharField(
        label='Natureza do processo',
        widget=forms.TextInput(attrs={
            'class': 'form-control form-control-alternative'}),
        required=False
    )

    parecer = forms.CharField(
        label='Parecer',
        widget=forms.TextInput(attrs={
            'class': 'form-control form-control-alternative'}),
        required=False
    )

    user_data = forms.ModelChoiceField(
        label='Dados cadastrados',
        widget=forms.Select(
            attrs={'class': 'form-control'}
        ),
        queryset=UserData.objects.all(),
        required=True
    )

src/processos/views.py
import json

from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout as logout_user
from django.http import HttpResponseForbidden, Http404, HttpResponse
from django.shortcuts import render, redirect, reverse
from django.views import generic
from django.urls import reverse_lazy
from .forms import CustomUserCreateForm, UserDataForm, ProcessoForm
from .models import UserData, Processo

# Create your views here.
tipos_processos_legenda = {
    'aproveitamento': 'Aproveitamento de Estudos',
    'adocao': 'Adoção do Nome Social',
    'desistencia': 'Desistência definitiva do Curso',
    'dilatacao': 'Dilatação do Prazo Máximo para Conclusão do Curso',
    'tirocinio_dispoensa': 'Dispensa de Tirocínio Docente',
    'superior_mat': 'Matrícula como Pordator de Diploma de Nível Superior de caráter especial',
    'ingresso_mat': 'Matrícula de Ingresso através de Processo Seletivo de Vagas Residuais',
    'permanencia': 'Permanência no Curso',
    'reconcideracao': 'Reconsideração de despacho/Recurso',
    'retificacao': 'Retificação de Histórico',
    'ex_oficio_transferencia': 'Transferência "ex-officio"',
    'especial_transferencia': 'Transferência Interna de Caráter Especial',
    'pos_transferencia': 'Transferência "ex-officio"',
    'trancamento': 'Trancamento',
    'trancamento-parcial': 'Parcial de inscrição em disciplinas',
    'trancamento-total': 'Total de inscrição em disciplinas (semestre corrente)',
    'trancamento-tempo': 'Por tempo determinado'
}


def home(request):
    return render(request, 'index.html')

def logout(request):
    logout_user(request)

    return redirect('home')

@login_required
def get_user_processos(request):
    processos = Processo.objects.filter(aluno=request.user).all()

    for processo in processos:
        tipos = processo.tipo_processo.split(',')
        new_tipos = ''

        for tipo in tipos:
            new_tipos += tipos_processos_legenda[tipo] + ', ' if tipo in tipos_processos_legenda else ''
        
        new_tipos = new_tipos[:-2]

        if 'outros' in processo.tipo_processo:
            new_tipos += ', Outros'

        setattr(processo, 'tipo_processo', new_tipos)

    return render(request, 'processos.html', {'processos': processos})

@login_required
def add_user_processo(request):
    if request.method == 'POST':
        form = ProcessoForm(request.POST)

        if form.is_valid():
            obj = form.save(commit=False)
            tipos = ''

            for tipo in request.POST.getlist('tipos[]'):
                tipos += tipo + ','

            obj.tipo_processo = tipos
            obj.aluno = request.user
            obj.save()

            return redirect('processos')
        else:
            print(form.errors)
    else:
        form = ProcessoForm()

    return render(request, 'processos_add_edit.html', {'form': form})

@login_required
def edit_user_processo(request, id_processo):
    try:
        processo = Processo.objects.get(id=id_processo)
    except Processo.DoesNotExist:
        raise Http404('Processo inexistente')

    if processo.aluno != request.user:
        return HttpResponseForbidden('Não autorizado')

    if request.method == 'POST':
        form = ProcessoForm(request.POST, instance=processo)

        if form.is_valid():
            obj = form.save(commit=False)
            tipos = ''

            for tipo in request.POST.getlist('tipos[]'):
                tipos += tipo + ','

            tipos = tipos[:-1]
            if 'outros' in request.POST['tipos[]']:
                tipos += ':' + request.POST['outros']

            obj.tipo_processo = tipos
            obj.save()

            return redirect('processos')
        else:
            print(form.errors)
    else:
        form = ProcessoForm(instance=processo)

    return render(request, 'processos_add_edit.html', {'form': form})

@login_required
def clone_user_processo(request):
    id_processo = request.POST['id']

    try:
        processo = Processo.objects.get(id=id_processo)
    except Processo.DoesNotExist:
        raise Http404('Processo inexistente')

    if processo.aluno != request.user:
        return HttpResponseForbidden('Não autorizado')

    processo.pk = None
    processo.save()

    return HttpResponse(json.dumps({'url': reverse('processos')}), content_type='application/json')

@login_required
def remove_user_processo(request):
    id_processo = request.POST['id']

    try:
        processo = Processo.objects.get(id=id_processo)
    except Processo.DoesNotExist:
        raise Http404('Processo inexistente')

    if processo.aluno != request.user:
        return HttpResponseForbidden('Não autorizado')

    processo.delete()

    return HttpResponse(json.dumps({'url': reverse('processos')}), content_type='application/json')

@login_required
def view_user_processo(request, id_processo):
    try:
        processo = Processo.objects.get(id=id_processo)
    except Processo.DoesNotExist:
        raise Http404('Processo inexistente')

    if processo.aluno != request.user:
        return HttpResponseForbidden('Não autorizado')

    return render(request, 'processos_view.html', {
        'user_data': processo.user_data,
        'processo': processo
    })

def requerimento(request, id_processo):
    try:
        processo = Processo.objects.get(id=id_processo)
    except Processo.DoesNotExist:
        raise Http404('Processo inexistente')

    if processo.aluno != request.user:
        return HttpResponseForbidden('Não autorizado')

    return render(request, 'requerimento_escolar.html', {
        'processo': processo
    })

@login_required
def get_user_data(request):
    user_data = UserData.objects.filter(aluno=request.user).all()

    return render(request, 'data.html', { 'user_data': user_data })

@login_required
def add_user_data(request):
    if request.method == 'POST':
        form = UserDataForm(request.POST)

        if form.is_valid():
            obj = form.save(commit=False)
            obj.aluno = request.user
            obj.save()

            return redirect('user_data')
        else:
            print(form.errors)
    else:
        form = UserDataForm()

    return render(request, 'data_add_edit.html', {'form': form})

@login_required
def edit_user_data(request, id_data):
    try:
        user_data = UserData.objects.get(id=id_data)
    except Processo.DoesNotExist:
        raise Http404('Dado inexistente')

    if user_data.aluno != request.user:
        return HttpResponseForbidden('Não autorizado')

    if request.method == 'POST':
        form = UserDataForm(request.POST, instance=user_data)

        if form.is_valid():
            obj = form.save(commit=False)
            obj.aluno = request.user
            obj.save()

            return redirect('user_data')
        else:
            print(form.errors)
    else:
        form = UserDataForm(instance=user_data)

    return render(request, 'data_add_edit.html', {
        'form': form,
        'add': False
    })

class Registro(generic.CreateView):
    form_class = CustomUserCreateForm
    success_url = reverse_lazy('home')
    template_name = 'registration/registration.html'

src/processos/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Sistemas de processos - UFBA</title>
  <!-- Favicon -->
  <link href="{% static '/img/brand/favicon.png' %}" rel="icon" type="image/png">
  <!-- Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
  <!-- Icons -->
  <link href="{% static 'vendor/nucleo/css/nucleo.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/@fortawesome/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
  <!-- Argon CSS -->
  <link type="text/css" href="{% static 'css/argon.css' %}" rel="stylesheet">
  <link type="text/css" href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
  <!-- Sidenav -->
  {% block sidenav %} {% endblock %}
  <!-- Main content -->
  <div class="main-content">
    {% block content %} {% endblock %}
  </div>
  <!-- Argon Scripts -->
  <!-- Core -->
  <script src="{% static '/vendor/jquery/dist/jquery.min.js' %}"></script>
  <script src="{% static '/vendor/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
  <!-- Optional JS -->
  <script src="{% static '/vendor/chart.js/dist/Chart.min.js' %}"></script>
  <script src="{% static '/vendor/chart.js/dist/Chart.extension.js' %}"></script>
  <!-- Argon JS -->
  <script src="https://unpkg.com/ionicons@4.5.5/dist/ionicons.js"></script>
  <script src="{% static '/js/argon.min.js' %}"></script>
  {% block js%} {% endblock %}
</body>

</html>

src/processos/templates/data.html
{% extends "base.html" %}
{% load static %}

{% block sidenav %}
  {% include "sidenav.html" %}
{% endblock %}

{% block content %}
    <!-- Top navbar -->
    {% include 'topbar.html' %}
    <!-- Header -->
    <div class="header bg-gradient-primary pb-8 pt-5 pt-md-8">
      <div class="container-fluid">
        <div class="header-body"></div>
      </div>
    </div>
    <!-- Page content -->
    <div class="container-fluid mt--7">
      <div class="row">
        {% include 'data_table.html' %}
      </div>
    </div>

    <div class="modal fade" id="modal-remove" tabindex="-1" role="dialog" aria-labelledby="modal-default" aria-hidden="true">
      <div class="modal-dialog modal- modal-dialog-centered modal-" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h6 class="modal-title" id="modal-title-default" style="font-size: 1rem;">Remover dados</h6>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">
            <p>Deseja realmente remover estes dados?</p>
          </div>
          <div class="modal-footer">
            <button id="confirmar-remove" type="button" class="btn btn-primary">Confirmar</button>
            <button type="button" class="btn btn-link  ml-auto" data-dismiss="modal">Cancelar</button> 
          </div>
        </div>
    </div>
{% endblock %}

{% block js %}
  <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
  <script src="{% static '/js/processos.js' %}"></script>
{% endblock %}

src/processos/templates/data_table.html
<div class="col">
    <div class="card shadow">
    <div class="card-header border-0">
        <div class="row align-items-center">
            <div class="col">
                <h3 class="mb-0">Dados cadastrados</h3>
            </div>
            <div class="col text-right">
                <a href="{% url 'add_user_data' %}" class="btn btn-sm btn-primary">Novo</a>
            </div>
            </div>
    </div>
    <div class="table-responsive">
        <table class="table align-items-center table-flush">
        <thead class="thead-light">
            <tr>
            <th scope="col">ID</th>
            <th scope="col">Nome</th>
            <th scope="col">Documento</th>
            <th scope="col">Endereço</th>
            <th scope="col">Curso</th>
            <th class="text-center" scope="col">Opções</th>
            </tr>
        </thead>
        <tbody>
            {% for data in user_data %}
            <tr>
                <td>{{ data.id }}</td>
                <td>{{ data.nome }}</td>
                <td>{{ data.doc_identificacao }}</td>
                <td>{{ data.endereco }}</td>
                <td>{{ data.curso }}</td>
                <td class="text-center">
                    <button id="edit-{{ data.id }}" class="btn-edit btn btn-sm btn-icon btn-2 btn-primary" type="button">
                        <span class="btn-inner--icon"><ion-icon name="create"></ion-icon></span>
                    </button>
                    <button id="delete-{{ data.id }}" class="btn-delete btn btn-sm btn-icon btn-2 btn-warning" type="button">
                        <span class="btn-inner--icon"><ion-icon name="trash"></ion-icon></span>
                    </button>
                </td>
            </tr>
            {% endfor %}
        </tbody>
        </table>
    </div>
    <div class="card-footer py-4">
    </div>
    </div>
</div>

src/processos/templates/processos_view.html
{% extends "base.html" %}
{% load static %}

{% block sidenav %}
  {% include "sidenav.html" %}
{% endblock %}

{% block content %}
    <!-- Top navbar -->
    {% include 'topbar.html' %}
    <!-- Header -->
    <div class="header bg-gradient-primary pb-8 pt-5 pt-md-8">
      <div class="container-fluid">
        <div class="header-body"></div>
      </div>
    </div>
    <!-- Page content -->
    <div class="container-fluid mt--7 pb-5">
        <div class="card bg-secondary shadow">
            <div class="card-header bg-white border-0">
              <div class="row align-items-center">
                <div class="col-8">
                  <h3 class="mb-0">Visualizar processo</h3>
                </div>
              </div>
            </div>
            <div class="card-body">
                {% csrf_token %}
                <h6 class="heading-small text-muted mb-4">Dados pessoais</h6>
                <div class="pl-lg-4">
                  <div class="row">
                    <div class="col-lg-12">
                      <div class="form-group focused">
                        {{ user_data.nome }}
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-lg-3">
                        {{ user.matricula }}
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group focused">
                        {{ user_data.doc_identificacao }}
                      </div>
                    </div>
                    <div class="col-lg-3">
                      <div class="form-group focused">
                        {{ user_data.doc_tipo }}
                      </div>
                    </div>
                  </div>
                </div>
                <hr class="my-4">
                <h6 class="heading-small text-muted mb-4">Endereço</h6>
                <div class="pl-lg-4">
                  <div class="row">
                    <div class="col-md-12">
                      <div class="form-group focused">
                        {{ user_data.endereco }}
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-lg-4">
                      <div class="form-group focused">
                       {{ user_data.bairro }}
                      </div>
                    </div>
                    <div class="col-lg-4">
                      <div class="form-group focused">
                        {{ user_data.cep }}
                      </div>
                    </div>
                    <div class="col-lg-4">
                      <div class="form-group">
                        {{ user_data.telefone }}
                      </div>
                    </div>
                  </div>
                </div>
                <hr class="my-4">
                <h6 class="heading-small text-muted mb-4">Curso</h6>
                <div class="pl-lg-4">
                  <div class="form-group focused">
                    {{ user_data.curso }}
                  </div>
                </div>
                <hr class="my-4">
                <div style="display: none"><textarea name="tipo_processo" cols="40" rows="10" id="id_tipo_processo">{{ processo.tipo_processo }}</textarea></div>
                <h6 class="heading-small text-muted mb-4">Objeto do Requerimento</h6>
                <div class="row">
                    <div class="col">
                        <div class="custom-control custom-control-alternative custom-checkbox mb-3">
                            <input class="custom-control-input" disabled name="tipos[]" value="aproveitamento" id="aproveitamento" type="checkbox">
                            <label class="custom-control-label" for="aproveitamento">Aproveitamento de Estudos</label>
                        </div>
                        <div class="custom-control custom-control-alternative custom-checkbox mb-3">
                            <input class="custom-control-input" disabled name="tipos[]" value="desistencia" id="desistencia" type="checkbox">
                            <label class="custom-control-label" for="desistencia">Desistência definitiva do Curso</label>
                        </div>
                        <div class="custom-control custom-control-alternative custom-checkbox mb-3">
                            <input class="custom-control-input" disabled name="tipos[]" value="dilatacao" id="dilatacao" type="checkbox">
                            <label class="custom-control-label" for="dilatacao">Dilatação do Prazo Máximo para Conclusão do Curso</label>
                        </div>
                        <div class="custom-control custom-control-alternative custom-checkbox mb-3">
                            <input class="custom-control-input" disabled name="tipos[]" value="pre_dispensa" id="pre_dispensa" type="checkbox">
                            <label class="custom-control-label" for="pre_dispensa">Dispensa de Tirocínio Docente</label>
                        </div>
                        <div class="custom-control custom-control-alternative custom-checkbox mb-3">
                            <input class="custom-control-input" disabled name="tipos[]" value="superior_mat" id="superior_mat" type="checkbox">
                            <label class="custom-control-label" for="superior_mat">Matrícula como Pordator de Diploma de Nível Superior de caráter especial</label>
                        </div>
                        <div class="custom-control custom-control-alternative custom-checkbox mb-3">
                            <input class="custom-control-input" disabled name="tipos[]" value="ingresso_mat" id="ingresso_mat" type="checkbox">
                            <label class="custom-control-label" for="ingresso_mat">Matrícula de Ingresso através de Processo Seletivo de Vagas Residuais</label>
                        </div>
                        <div class="custom-control custom-control-alternative custom-checkbox mb-3">
                            <input class="custom-control-input" disabled name="tipos[]" value="permanencia" id="permanencia" type="checkbox">
                            <label class="custom-control-label" for="permanencia">Permanência no Curso</label>
                        </div>
                    </div>
                    <div class="col">
                        <div class="custom-control custom-control-alternative custom-checkbox mb-3">
                            <input class="custom-control-input" disabled name="tipos[]" value="reconcideracao" id="reconcideracao" type="checkbox">
                            <label class="custom-control-label" for="reconcideracao">Reconsideração de despacho/Recurso</label>
                        </div>
                        <div class="custom-control custom-control-alternative custom-checkbox mb-3">
                            <input class="custom-control-input" disabled name="tipos[]" value="retificacao" id="retificacao" type="checkbox">
                            <label class="custom-control-label" for="retificacao">Retificação de Histórico</label>
                        </div>
                        <div class="custom-control custom-control-alternative custom-checkbox mb-3">
                            <input class="custom-control-input" disabled name="tipos[]" value="ex_oficio_transferencia" id="ex_oficio_transferencia" type="checkbox">
                            <label class="custom-control-label" for="ex_oficio_transferencia">Transferência "ex-officio"</label>
                        </div>
                        <div class="custom-control custom-control-alternative custom-checkbox mb-3">
                            <input class="custom-control-input" disabled name="tipos[]" value="especial_transferencia" id="especial_transferencia" type="checkbox">
                            <label class="custom-control-label" for="especial_transferencia">Transferência Interna de Caráter Especial</label>
                        </div>
                        <div class="custom-control custom-control-alternative custom-checkbox mb-3">
                            <input class="custom-control-input" disabled name="tipos[]" value="pos_transferencia" id="pos_transferencia" type="checkbox">
                            <label class="custom-control-label" for="pos_transferencia">Transferência Pós-Graduação</label>
                        </div>
                        <div class="custom-control custom-control-alternative custom-checkbox mb-3">
                            <input class="custom-control-input" disabled name="tipos[]" value="trancamento" id="trancamento" type="checkbox">
                            <label class="custom-control-label" for="trancamento">Trancamento</label>
                        </div>
                        <div class="custom-control custom-control-alternative custom-checkbox mb-3">
                            <input class="custom-control-input" disabled name="tipos[]" value="trancamento-parcial" id="trancamento-parcial" type="checkbox">
                            <label class="custom-control-label" for="trancamento-parcial">Parcial de inscrição em disciplinas</label>
                        </div>
                        <div class="custom-control custom-control-alternative custom-checkbox mb-3">
                            <input class="custom-control-input" disabled name="tipos[]" value="trancamento-total" id="trancamento-total" type="checkbox">
                            <label class="custom-control-label" for="trancamento-total">Total de inscrição em disciplinas <small>(semestre corrente)</small></label>
                        </div>
                        <div class="custom-control custom-control-alternative custom-checkbox mb-3">
                            <input class="custom-control-input" disabled name="tipos[]" value="trancamento-tempo" id="trancamento-tempo" type="checkbox">
                            <label class="custom-control-label" for="trancamento-tempo">Por tempo determinado</label>
                        </div>
                    </div>
                </div>
                <div class="custom-control custom-control-alternative custom-checkbox mb-3">
                    <input class="custom-control-input" disabled value="outros" id="outros" type="checkbox">
                    <label class="custom-control-label" for="outros">Outros</label>
                    <p id="outros_justificativa"></p>
                </div>
                <div class="form-group focused">
                    <label>Esclarecimentos:</label><br/>
                    {{ processo.esclarecimentos }}
                </div>
                <hr class="my-4">
                <div class="form-group focused">
                    <label>Número do processo:</label>
                    {{ processo.numero }}
                </div>
                <div class="form-group focused">
                    <label>Natureza do processo:</label>
                    {{ processo.natureza_processo }}
                </div>
                <div class="form-group focused">
                    <label>Parecer:</label>
                    {{ processo.parecer }}
                </div>
                <button id="btn-imprimir" class="float-right btn btn-icon btn-3 btn-primary" type="button">
                  <span class="btn-inner--icon"><ion-icon name="print"></ion-icon></span>
                  <span class="btn-inner--text">Imprimir</span>
                </button>
            </div>            
        </div>
    </div>
{% endblock %}

{% block js %}
  <script src="{% static '/js/processos_view.js' %}"></script>
{% endblock %}